name: krl_schedule_with_gemini_ai
description: "Jalan Santuy, Jadwal KRL di Tanganmu!"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  device_preview: ^1.2.0
  flutter:
    sdk: flutter
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/stations.json
